// next-sudoku/src/components/Cell.tsx
import { useState } from "react";
import type { CellProps } from "./CellProps";

export function Cell(props: CellProps) {
  const [localValue, setLocalValue] = useState(props.value);
  const borderedIndices: Array<number> = [2,5,8];
  const getClassName = () => {
    let className = "cell";
    if (!props.isDefault && !props.isValid) {
      className += " cell--invalid";
    }
    if (borderedIndices.includes(props.colIndex)) {
      className += " cell--extra-right-border";
    }
    if (borderedIndices.includes(props.rowIndex)) {
      className += " cell--extra-bottom-border";
    }
    if(props.rowIndex === 0) {
      className += " cell--extra-top-border";
    }
    if(props.colIndex === 0) {
      className += " cell--extra-left-border";
    }
    return className;
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    if (newValue === '') {
      setLocalValue(null);
      props.handleValueChange(props.rowIndex, props.colIndex, null);
    } else if (isNaN(Number(newValue)) || Number(newValue) < 1 || Number(newValue) > 9) {
      //ignore
    } else {
      setLocalValue(Number(newValue));
      props.handleValueChange(props.rowIndex, props.colIndex, Number(newValue));
    }
  }

  return (
    <>
    { props.isDefault && (
      <div className={getClassName()}>
      { props.value }
      </div>
      )
    }
    { !props.isDefault && (
      <input
        type="text"
        value={localValue == null ? '' : localValue.toString()}
        onChange={handleInputChange}
        className={"cell-input " + getClassName()}
        maxLength="1"
      />
    )}
    </>
  )
}

// sudoku-vue/src/components/Cell.vue
<script lang="ts">
export default {
    props: {
        rowIndex: Number,
        columnIndex: Number,
        value: Number,
        isDisabled: Boolean,
        isValid: Boolean
    },
    data() {
        return {
            stringValue: this.$props.value === 0 ? "" : this.$props.value!.toString()
        }
    },
    methods: {
        onValueChange: function(e: Event){
            var element = e.target as HTMLInputElement;
            if(!element.value){
                e.preventDefault();
                e.stopPropagation();
                return;
            }
            const numberValue = parseInt(element.value);
            if(isNaN(numberValue)){
                e.preventDefault();
                e.stopPropagation();
                return;
            }
            if(numberValue !== 0) {
                this.stringValue = numberValue.toString();
                this.$emit('valueChanged', this.rowIndex, this.columnIndex, numberValue);
            }
            else {
                e.preventDefault();
                e.stopPropagation();
            }
        },
        onFocus: function(e: Event){
            const element = e.target as HTMLInputElement;
            if(element.value === "0"){
                element.value = "";
            }
        },
        getClassName: function(){
            //console.log(`getClassName. isValid = ${this.isValid}`);
            if(this.isDisabled) return "cell disabled";
            return this.isValid ? "cell valid" : "cell invalid";
        }
    },
    emits: ['valueChanged']
}
</script>
<template>
    <input type="text" :disabled="isDisabled" @input="onValueChange" :value="stringValue"
    maxlength="1" :className="getClassName()" />
</template>
